# Generated by Django 4.1.3 on 2022-11-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_remove_todo_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='done',
            new_name='is_done',
        ),
    ]
