# Generated by Django 4.1.3 on 2022-11-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_remove_todo_is_done_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('todo', 'Todo')], default='todo', max_length=10),
        ),
    ]
